# -*- coding: utf-8 -*-
"""CS335_PythonLab1_IsraelNorman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gioyNC49p2Vz9Av6H_KufenhPq7Ra-44
"""

name = "Israel Norman"
age = 27
ai_course = True

print("Name:", name)
print("Age in 5 years:", age + 5)
print("Is enrolled in CS 335 course?", ai_course)
print()

#Below is the sentence example with all three values!
print(name, "is ", age, ". Is he enrolled in CS 335?", ai_course,"!")
print()

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "Robotics", "Computer Vision"]
for topic in topics: print("We will study:", topic)
print()

#Below is a list example with numbers
for i, topic in enumerate(topics): print(i + 1, ":", topic)
print()

#Added an A+ tier to see if it works.
student = {"name": "Israel", "score": 99}
if student["score"] > 95:
  grade = "A+!? NICE"
elif student["score"] > 90:
  grade = "A"
elif student["score"] >= 80:
  grade = "B"
else:
  grade = "C or below"

print(f"{student['name']} received a grade of {grade}.")

def greet_student(name):
  return f"Welcome to CS 335, {name}!"
# Test
print(greet_student("Israel"))
print()

#Testing squaring a number
def square_number(num):
  return num * num
print("The square of 8 is:", square_number(8))
print()
print("The square of 777 is:", square_number(777))

